// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getPassword.sql

package databases

import (
	"context"
)

const getPassword = `-- name: GetPassword :one
SELECT hashed_password FROM users
WHERE email = $1
`

func (q *Queries) GetPassword(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPassword, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
