// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getUserFromToken.sql

package databases

import (
	"context"

	"github.com/google/uuid"
)

const getUserFromToken = `-- name: GetUserFromToken :one
SELECT user_id FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetUserFromToken(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, token)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
